// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_PersonIntro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_PersonIntro));
        
        string IMigrationMetadata.Id
        {
            get { return "202206302040009_mig_PersonIntro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
